config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index" 
  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :stock_product_destinations, only: [:create]
  end
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:show, :index, :new, :create]

  resources :orders, only: [:new, :create, :show, :index, :edit, :update] do
    resources :order_items, only: [:new, :create]
    get 'search', on: :collection
    member do
      post 'delivered'
      post 'canceled'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: [:show, :index, :create]
    end
  end
end

app/models/product_model.rb
class ProductModel < ApplicationRecord
  belongs_to :supplier
  has_many :order_items
  has_many :orders, through: :order_items
  validates :name, :weight, :height, :width, :depth, :sku, :supplier, presence: true
end

app/controllers/product_models_controller.rb
class ProductModelsController < ApplicationController
  before_action :authenticate_user!, only: [:index]
  def index
    @product_models = ProductModel.all
  end

  def show
    @product_model = ProductModel.find(params[:id])
  end

  def new
    @product_model = ProductModel.new
    @supplier = Supplier.all
  end

  def create
    @product_model = ProductModel.new(get_params)
    if @product_model.save
      redirect_to @product_model, notice: 'Modelo de Produto cadastrado com sucesso'
    else
      @supplier = Supplier.all
      flash.now[:notice] = 'Não foi possível cadastrar o modelo de produto.'
      render 'new'
    end
  end

  def get_params
    params.require(:product_model).permit(:name, :weight, :height, :width, :depth, :sku, :supplier_id)
  end
end

app/views/product_models/index.html.erb
<h1>Modelos de Produtos</h1>

<%= link_to 'Cadastrar Novo', new_product_model_path %>

<% if @product_models.any? %>
  <% @product_models.each do |pm| %>
    <div>
      <h2><%= pm.name %></h2>
      <dl>
        <dt>SKU</dt>
        <dd><%= pm.sku %></dd>
        <dt>Fornecedor</dt>
        <dd><%= pm.supplier.brand_name %></dd>
      </dl>
    </div>
  <% end %>
<% else %>
  <p>Nenhum modelo de produto cadastrado.</p>
<% end %>

app/views/product_models/new.html.erb
<h1>Cadastrar Novo Modelo de Produto</h1>

<%= form_with(model: @product_model) do |f|%>
  <div>
    <%= f.label :name%>
    <%= f.text_field :name%>
  </div>
  <div>
    <%= f.label :weight%>
    <%= f.number_field :weight%>
  </div>
  <div>
    <%= f.label :height%>
    <%= f.number_field :height%>
  </div>
  <div>
    <%= f.label :width%>
    <%= f.number_field :width%>
  </div>
   <div>
    <%= f.label :depth%>
    <%= f.number_field :depth%>
  </div>
  <div>
    <%= f.label :sku%>
    <%= f.text_field :sku%>
  </div>
  <div>
    <%= f.label :supplier_id%>
    <%= f.collection_select :supplier_id, @supplier, :id, :brand_name%>
  </div>
  <%= f.submit 'Enviar'%>
<% end %>

app/views/product_models/show.html.erb
<h1><%= @product_model.name %></h1>

<dl>
  <dt>Fornecedor:</dt>
  <dd><%= @product_model.supplier.brand_name%></dd>
  <dt>SKU:</dt>
  <dd><%= @product_model.sku%></dd>
  <dt>Dimensão:</dt>
  <dd><%= @product_model.height%>cm x <%= @product_model.width%>cm x <%= @product_model.depth%>cm</dd>
  <dt>Peso:</dt>
  <dd><%= @product_model.weight%>g</dd>
</dl>