config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index" 
  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :stock_product_destinations, only: [:create]
  end
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:show, :index, :new, :create]

  resources :orders, only: [:new, :create, :show, :index, :edit, :update] do
    resources :order_items, only: [:new, :create]
    get 'search', on: :collection
    member do
      post 'delivered'
      post 'canceled'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: [:show, :index, :create]
    end
  end
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :product_models
  validates :corporate_name, :brand_name, :registration_number, :full_address, :city, :state, :email, presence: true  

  def full_description
    "#{brand_name} - #{corporate_name} - #{registration_number}"
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  def index
    @suppliers = Supplier.all
  end

  def show
    @supplier = Supplier.find(params[:id])
  end

  def new
    @supplier = Supplier.new
  end

  def create
    @supplier = Supplier.new(supplier_params)
    if @supplier.save
      redirect_to @supplier, notice: 'Fornecedor cadastrado com sucesso.'
    else
      flash.now[:notice] = 'Fornecedor não cadastrado.'
      render 'new'
    end
  end

  def edit
    @supplier = Supplier.find(params[:id])
  end

  def update
    @supplier = Supplier.find(params[:id])
    if @supplier.update(supplier_params)
      redirect_to @supplier, notice: 'Fornecedor cadastrado com sucesso.'
    else
      flash.now[:notice] = 'Fornecedor não cadastrado.'
      render 'edit'
    end
  end

  def supplier_params
    params.require(:supplier).permit(:corporate_name, :brand_name, :registration_number, :full_address, :city, :state, :email)
  end
end

app/views/suppliers/edit.html.erb
<h1>Editar Fornecedor</h1>
<%= form_with(model: @supplier) do |f| %>
  <div>
    <%= f.label :corporate_name %>
    <%= f.text_field :corporate_name %>
  </div>
  <div>
    <%= f.label :brand_name %>
    <%= f.text_field :brand_name %>
  </div>
  <div>
    <%= f.label :full_address %>
    <%= f.text_field :full_address %>
  </div>
  <div>
    <%= f.label :registration_number %>
    <%= f.text_field :registration_number %>
  </div>
  <div>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  <div>
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.submit 'Enviar' %>
  </div>
<% end %>

app/views/suppliers/index.html.erb
<h1>Fornecedores</h1>

<% if @suppliers.any? %>
 <table>
    <thead>
      <tr>
        <th>Nome</th>
        <th>Localização</th>
      </tr>
    </thead>
    <tbody>
        <td><% @suppliers.each do |s|%></td>
          <tr>
            <td><%= link_to s.brand_name, s%></td>
            <td><%= s.city%> - <%= s.state%></td>
          </tr>
        <% end %>
    </tbody>
 </table>
 <% else %>
  <p>Não existem fornecedores cadastrados</p>
 <% end %>

 <%= link_to 'Cadastrar novo fornecedor', new_supplier_path %>

app/views/suppliers/new.html.erb
<h1>Novo Fornecedor</h1>

<% if @supplier.errors.any? %>
<p>Verifique os erros abaixo</p>
  <ul>
    <% @supplier.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <%end%>
  </ul>
<% end %>

<%= form_with(model: @supplier) do |f| %>
  <div>
    <%= f.label :corporate_name %>
    <%= f.text_field :corporate_name %>
  </div>
  <div>
    <%= f.label :brand_name %>
    <%= f.text_field :brand_name %>
  </div>
  <div>
    <%= f.label :full_address %>
    <%= f.text_field :full_address %>
  </div>
  <div>
    <%= f.label :registration_number %>
    <%= f.text_field :registration_number %>
  </div>
  <div>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  <div>
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.submit 'Enviar' %>
  </div>
<% end %>

app/views/suppliers/show.html.erb
<h1>Fornecedor <%= @supplier.brand_name%></h1>
<h2><%= @supplier.corporate_name%></h2>

<dl>
  <dt>Documento:</dt>
  <dd><%= @supplier.registration_number %></dd>
  <dt>Endereço:</dt>
  <dd><%= @supplier.full_address %> - <%= @supplier.city%> - <%= @supplier.state%></dd>
  <dt>E-mail:</dt>
  <dd><%= @supplier.email %></dd>
</dl>

<%= link_to 'Editar', edit_supplier_path(@supplier) %>

<div>
  <%= link_to 'Voltar', root_path %>
</div>