config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index" 
  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :stock_product_destinations, only: [:create]
  end
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:show, :index, :new, :create]

  resources :orders, only: [:new, :create, :show, :index, :edit, :update] do
    resources :order_items, only: [:new, :create]
    get 'search', on: :collection
    member do
      post 'delivered'
      post 'canceled'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: [:show, :index, :create]
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WarehouseApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <header>
      <%= link_to root_path do %>
        <h1>Galpões & Estoque</h1>
      <% end %>
      <nav>
        <%= link_to 'Fornecedores', suppliers_path%> |
        <%= link_to 'Modelos de Produtos', product_models_path%> |
        <%= link_to 'Registrar Pedido', new_order_path%> | 
        <%= link_to 'Meus Pedidos', orders_path%>

        <% if user_signed_in? %>

          <%= form_with(url: search_orders_path, method: :get) do |f| %>
            <%= f.label :query, 'Buscar Pedido' %>
            <%= f.text_field :query %>
            <%= f.submit 'Buscar'%>
          <% end %>

          <%= current_user.description%> |
          <%= button_to 'Sair', destroy_user_session_path, method: :delete%>

        <% else %>
          <%= link_to 'Entrar', new_user_session_path%>
        <% end %>
      </nav>
    </header>
    <main>
      <div>
        <%= flash[:alert] %>
        <%= flash[:notice] %>
      </div>
      <%= yield %>
    </main>
  </body>
</html>